import * as types from '../mutation-types'

const authors = {
  fir:{
    title:'@IT·互联网',
    img:'../../static/img/hot2.jpg',
    info:{recordCount:47107,followCount:1460560},
    articleLists:{
      newestCommands:[{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      }],
      newestRecords:[{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      }],
      hots:[{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      }]
    }
  },
  sec:{
    title:'人文社科',
    img:'../../static/img/hot1.jpg',
    info:{recordCount:3234,followCount:2133443},
    articleLists:{
      newestCommands:[{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      }],
      newestRecords:[{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      }],
      hots:[{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      }]
    }
  },
  thir:{
    title:'读书',
    img:'../../static/img/hot3.jpg',
    info:{recordCount:3234,followCount:2133443},
    articleLists:{
      newestCommands:[{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      }],
      newestRecords:[{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      }],
      hots:[{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      }]
    }
  },
  fourth:{
    title:'手绘',
    img:'../../static/img/hot4.jpg',
    info:{recordCount:3234,followCount:2133443},
    articleLists:{
      newestCommands:[{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      }],
      newestRecords:[{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      }],
      hots:[{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      }]
    }
  },
  fifth:{
    title:'旅行·在路上',
    img:'../../static/img/hot5.png',
    info:{recordCount:3234,followCount:2133443},
    articleLists:{
      newestCommands:[{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      }],
      newestRecords:[{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      }],
      hots:[{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      }]
    }
  },
  sixth:{
    title:'故事',
    img:'../../static/img/hot6.jpg',
    info:{recordCount:3234,followCount:2133443},
    articleLists:{
      newestCommands:[{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      }],
      newestRecords:[{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      }],
      hots:[{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      }]
    }
  },
  seventh:{
    title:'历史',
    img:'../../static/img/hot7.jpg',
    info:{recordCount:3234,followCount:2133443},
    articleLists:{
      newestCommands:[{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      }],
      newestRecords:[{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      }],
      hots:[{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      }]
    }
  }
};

const state = {
  authorInformation:[{
    title:'@IT·互联网',
    img:'../../static/img/hot2.jpg',
    info:{recordCount:0,followCount:0},
    articleLists:{
      newestCommands:[{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      },{
        title:'当CPU飙高时，它在做什么',
        content:'在开发过程中，有时候我们发现JVM占用的CPU居高不下，跟我们的预期不符，这时，CPU在做什么呢？是什么线程让CPU如此忙碌呢？我们通过如下几步，可以查看CPU在执行什么线程。',
        author:'刘振锋',
        command:4,
        like:43,
        admire:1,
        img:'../../static/img/author-newestCommand1.png'
      }],
      newestRecords:[{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      },{
        title:'Redisson是如何实现分布式锁的？',
        content:'针对项目中使用的分布式锁进行简单的示例配置以及源码解析，并列举源码中使用到的一些基础知识点，但是没有对redisson中使用到的netty知识进行解析。',
        author:'Java填坑之路',
        command:0,
        like:0,
        admire:0,
        img:'../../static/img/author-newestRecord1.png'
      }],
      hots:[{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      },{
        title:'这15个图片网站，至少让你的效率翻一倍！',
        content:'如果你还在用百度搜图，那真是“棒棒哒”，像你这么专一的人不多了。经常有人会问我，你一般在哪找的图片？不少朋友都会有自己的素材库，需要时提取就可以了。不过像我这么懒的人，图片分类都得好久，找图片就更费力了。',
        author:'七小葩',
        command:608,
        like:15652,
        admire:15,
        img:'../../static/img/author-hots1.jpg'
      }]
    }
  }]
};

const mutations = {
  [types.CONFIRM_AUTHOR](state,theme){
    switch (theme) {
      case '人文社科':
        state.authorInformation = [authors.fir];break;
      case '@IT·互联网':
        state.authorInformation = [authors.fir];break;
      case '读书':
        state.authorInformation = [authors.fir];break;
      case '手绘':
        state.authorInformation = [authors.fir];break;
      case '旅行·在路上':
        state.authorInformation = [authors.fir];break;
      case '故事':
        state.authorInformation = [authors.fir];break;
      case '历史':
        state.authorInformation = [authors.fir];break;
      default:
        state.authorInformation = [authors.fir];break;
    }
  }
};

export default{
  state,
  mutations
}
